// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHHWTXBu-CiRytqLg0tqRmNCHtsd66Vy0',
    appId: '1:517336120648:web:1af7616db80b1f9ea7477d',
    messagingSenderId: '517336120648',
    projectId: 'kita-hack-resource-finder',
    authDomain: 'kita-hack-resource-finder.firebaseapp.com',
    storageBucket: 'kita-hack-resource-finder.firebasestorage.app',
    measurementId: 'G-YCKXM3S2CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnYf5U9WHjlRrke7GAKTCSR1GXriUpGUc',
    appId: '1:517336120648:android:eae6bf70bbca13ada7477d',
    messagingSenderId: '517336120648',
    projectId: 'kita-hack-resource-finder',
    storageBucket: 'kita-hack-resource-finder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-EPIzmXt00CZU9TXaeNSDUNkhZ-_QFE',
    appId: '1:517336120648:ios:2f1befbbf8828160a7477d',
    messagingSenderId: '517336120648',
    projectId: 'kita-hack-resource-finder',
    storageBucket: 'kita-hack-resource-finder.firebasestorage.app',
    iosBundleId: 'com.example.resourceFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV-EPIzmXt00CZU9TXaeNSDUNkhZ-_QFE',
    appId: '1:517336120648:ios:2f1befbbf8828160a7477d',
    messagingSenderId: '517336120648',
    projectId: 'kita-hack-resource-finder',
    storageBucket: 'kita-hack-resource-finder.firebasestorage.app',
    iosBundleId: 'com.example.resourceFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHHWTXBu-CiRytqLg0tqRmNCHtsd66Vy0',
    appId: '1:517336120648:web:48ac18de0897583ba7477d',
    messagingSenderId: '517336120648',
    projectId: 'kita-hack-resource-finder',
    authDomain: 'kita-hack-resource-finder.firebaseapp.com',
    storageBucket: 'kita-hack-resource-finder.firebasestorage.app',
    measurementId: 'G-8RCQGZWFNT',
  );
}
